### ISSUE TITLE
Silence pathfinder.jl in tests

### ISSUE THREAD

**Issue by seabbs** [CDCgov/Rt-without-renewal#154]
We have near silent tests apart from the info statements in our pathfinder wrappers. It would be nice to silence these to make the test output easier to read. From a skim it seems like using `Logging.jl` might be the way to do this.

**Comment by SamuelBrand1** [comment]
Or `Suppressor.jl`?

**Comment by seabbs** [comment]
Yeah I looked at that and it looked like a good option. I assumed that the base option was the way to go but not totally clear on the +/-s

**Comment by SamuelBrand1** [comment]
> Yeah I looked at that and it looked like a good option. I assumed that the base option was the way to go but not totally clear on the +/-s

I think the only negative of `Suppressor.jl` is that its an extra dep; it does exactly what we want: silence some warnings in test that we otherwise want in general usage. I'm sure there is a why of intercepting log messages and downgrading them in tests, but Suppressor is pretty light weight and easy to use. 

Personally, I think its worth having as a dep for the `Test` env.
